
deploymentName: loans-deployment
deploymentLabel: loans

replicaCount: 1

image:
  repository: mmatejovic/loans
  tag: latest

containerPort: 8090

service:
  type: ClusterIP
  port: 8090
  targetPort: 8090

config_enabled: true
zipkin_enabled: true
profile_enabled: true
eureka_enabled: true
keycloak_enabled: false
