version: "3.8"

services:

  accounts:
    image: mmatejovic/account:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - mmario-network

  loans:
    image: mmatejovic/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - mmario-network

  cards:
    image: mmatejovic/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - mmario-network

networks:
  mmario-network: