version: "3.8"

services:

  configserver:
    image: mmatejovic/confserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - mmario-network
  eurekaserver:
    image: mmatejovic/eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
      - mmario-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  accounts:
    image: mmatejovic/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - mmario-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 150s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/


  loans:
    image: mmatejovic/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - mmario-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 150s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/


  cards:
    image: mmatejovic/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - mmario-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 150s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/


  gatewayserver:
    image: mmatejovic/gatewayserver:latest
    mem_limit: 700m
    ports:
      - "8072:8072"
    networks:
      - mmario-network
    depends_on:
      - configserver
      - eurekaserver
      - cards
      - loans
      - accounts
    deploy:
      restart_policy:
        condition: on-failure
        delay: 75s
        max_attempts: 3
        window: 200s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/



networks:
  mmario-network: